### ISSUE TITLE
Add HifiPoolRegistry deployment script

### ISSUE THREAD

**Issue by scorpion9979** [hifi-finance/hifi-deployers#1]
Add a script to deploy HifiPoolRegistry contract.
Depends on https://github.com/hifi-finance/hifi-amm/pull/19 and https://github.com/hifi-finance/hifi-amm/issues/20.

**Comment by PaulRBerg** [comment]
This is stale now, due to the recent migration to the [monorepo](https://github.com/hifi-finance/hifi). Please redo the work and make a PR against https://github.com/hifi-finance/hifi.
